image: rust:1.82.0

before_script:
  - cargo install mdbook

cache:
  paths:
    - .cargo

pages:
  script:
    - mdbook build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH